import Providers from "@/store/provider"
/* import {Montserrat} from "@next/font/google" */

/* const fuente = Montserrat({
  weight:'400',
  subsets: ['latin']
}) */

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="es">
      <Providers>
        <body /* className={fuente.className} */>{children}</body>
      </Providers>
    </html>
  )
}



/* EL MODULO FUE DEPRECADO por lo que te mencionan que ya esto estará incorporado en la versión 14*/